# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-20 15:53
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20191017_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='caption',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
